# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class Photo(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: builtin___int
    name = ... # type: typing___Text
    url = ... # type: typing___Text

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        url : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Photo: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"name",u"url"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"name",b"name",u"url",b"url"]) -> None: ...

class Category(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: builtin___int
    name = ... # type: typing___Text

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Category: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"name"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"name",b"name"]) -> None: ...

class Pet(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class PetStatus(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Pet.PetStatus': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Pet.PetStatus']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Pet.PetStatus']]: ...
        AVAILABLE = typing___cast('Pet.PetStatus', 0)
        PENDING = typing___cast('Pet.PetStatus', 1)
        BOOKED = typing___cast('Pet.PetStatus', 2)
        SOLD = typing___cast('Pet.PetStatus', 3)
    AVAILABLE = typing___cast('Pet.PetStatus', 0)
    PENDING = typing___cast('Pet.PetStatus', 1)
    BOOKED = typing___cast('Pet.PetStatus', 2)
    SOLD = typing___cast('Pet.PetStatus', 3)

    id = ... # type: builtin___int
    name = ... # type: typing___Text
    status = ... # type: Pet.PetStatus

    @property
    def category(self) -> Category: ...

    @property
    def photos(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Photo]: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        name : typing___Optional[typing___Text] = None,
        category : typing___Optional[Category] = None,
        photos : typing___Optional[typing___Iterable[Photo]] = None,
        status : typing___Optional[Pet.PetStatus] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Pet: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"category"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"category",u"id",u"name",u"photos",u"status"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"category",b"category"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"category",b"category",u"id",b"id",u"name",b"name",u"photos",b"photos",u"status",b"status"]) -> None: ...

class Customer(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class AccountStatus(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Customer.AccountStatus': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Customer.AccountStatus']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Customer.AccountStatus']]: ...
        ACTIVE = typing___cast('Customer.AccountStatus', 0)
        INACTIVE = typing___cast('Customer.AccountStatus', 1)
    ACTIVE = typing___cast('Customer.AccountStatus', 0)
    INACTIVE = typing___cast('Customer.AccountStatus', 1)

    id = ... # type: builtin___int
    first_name = ... # type: typing___Text
    last_name = ... # type: typing___Text
    email = ... # type: typing___Text
    status = ... # type: Customer.AccountStatus

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        first_name : typing___Optional[typing___Text] = None,
        last_name : typing___Optional[typing___Text] = None,
        email : typing___Optional[typing___Text] = None,
        status : typing___Optional[Customer.AccountStatus] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Customer: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"email",u"first_name",u"id",u"last_name",u"status"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"email",b"email",u"first_name",b"first_name",u"id",b"id",u"last_name",b"last_name",u"status",b"status"]) -> None: ...

class Order(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class OrderStatus(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Order.OrderStatus': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Order.OrderStatus']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Order.OrderStatus']]: ...
        PLACED = typing___cast('Order.OrderStatus', 0)
        APPROVED = typing___cast('Order.OrderStatus', 1)
        DELIVERED = typing___cast('Order.OrderStatus', 2)
    PLACED = typing___cast('Order.OrderStatus', 0)
    APPROVED = typing___cast('Order.OrderStatus', 1)
    DELIVERED = typing___cast('Order.OrderStatus', 2)

    id = ... # type: builtin___int
    status = ... # type: Order.OrderStatus

    @property
    def customer(self) -> Customer: ...

    @property
    def pet(self) -> Pet: ...

    @property
    def ship_date(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        id : typing___Optional[builtin___int] = None,
        customer : typing___Optional[Customer] = None,
        pet : typing___Optional[Pet] = None,
        ship_date : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        status : typing___Optional[Order.OrderStatus] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Order: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"customer",u"pet",u"ship_date"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"customer",u"id",u"pet",u"ship_date",u"status"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"customer",b"customer",u"pet",b"pet",u"ship_date",b"ship_date"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"customer",b"customer",u"id",b"id",u"pet",b"pet",u"ship_date",b"ship_date",u"status",b"status"]) -> None: ...
