# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import Message as google___protobuf___message___Message

from petstore.proto.petstore_pb2 import Pet as petstore___proto___petstore_pb2___Pet

from typing import Iterable as typing___Iterable, Optional as typing___Optional

from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

class GetPetRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    pet_id = ...  # type: builtin___int
    def __init__(self, *, pet_id: typing___Optional[builtin___int] = None) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> GetPetRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(
            self, field_name: typing_extensions___Literal["pet_id"]
        ) -> None: ...
    else:
        def ClearField(
            self, field_name: typing_extensions___Literal["pet_id", b"pet_id"]
        ) -> None: ...

class CreatePetRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def pet(self) -> petstore___proto___petstore_pb2___Pet: ...
    def __init__(
        self, *, pet: typing___Optional[petstore___proto___petstore_pb2___Pet] = None
    ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> CreatePetRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(
            self, field_name: typing_extensions___Literal["pet"]
        ) -> builtin___bool: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["pet"]
        ) -> None: ...
    else:
        def HasField(
            self, field_name: typing_extensions___Literal["pet", b"pet"]
        ) -> builtin___bool: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["pet", b"pet"]
        ) -> None: ...

class PetList(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    total_items = ...  # type: builtin___int
    @property
    def pets(
        self
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        petstore___proto___petstore_pb2___Pet
    ]: ...
    def __init__(
        self,
        *,
        total_items: typing___Optional[builtin___int] = None,
        pets: typing___Optional[
            typing___Iterable[petstore___proto___petstore_pb2___Pet]
        ] = None,
    ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> PetList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(
            self, field_name: typing_extensions___Literal["pets", "total_items"]
        ) -> None: ...
    else:
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "pets", b"pets", "total_items", b"total_items"
            ],
        ) -> None: ...

class ListPetRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    items_per_page = ...  # type: builtin___int
    page = ...  # type: builtin___int
    def __init__(
        self,
        *,
        items_per_page: typing___Optional[builtin___int] = None,
        page: typing___Optional[builtin___int] = None,
    ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> ListPetRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(
            self, field_name: typing_extensions___Literal["items_per_page", "page"]
        ) -> None: ...
    else:
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "items_per_page", b"items_per_page", "page", b"page"
            ],
        ) -> None: ...
